import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://login.salesforce.com/');
  await page.getByRole('textbox', { name: 'Username' }).fill('saikat@cloudkaptan.com.dev');
  await page.getByRole('textbox', { name: 'Password' }).fill('SD1234567');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.goto('https://ck-qe-dev-ed.develop.lightning.force.com/lightning/page/home');
  await page.getByRole('link', { name: 'Leads' }).dblclick();
  await page.getByRole('button', { name: 'New' }).click();
  await page.getByRole('combobox', { name: 'Salutation' }).click();
  await page.getByRole('option', { name: 'Mr.' }).locator('span').nth(1).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Rahoyl');
  await page.getByRole('textbox', { name: '*Last Name' }).click();
  await page.getByRole('textbox', { name: '*Last Name' }).fill('Ghposh');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('9807087456');
  await page.getByRole('textbox', { name: '*Company' }).click();
  await page.getByRole('textbox', { name: '*Company' }).fill('ck');
  await page.getByRole('combobox', { name: 'Lead Status' }).click();
  await page.getByText('Working - Contacted').click();
  await page.getByRole('combobox', { name: 'Lead Source' }).click();
  await page.getByRole('option', { name: 'Phone Inquiry' }).locator('span').nth(1).click();
  await page.getByRole('combobox', { name: 'Industry' }).click();
  await page.getByRole('option', { name: 'Banking' }).locator('span').nth(1).click();
  await page.getByRole('textbox', { name: 'No. of Employees' }).fill('90');
  await page.getByRole('combobox', { name: 'Rating' }).click();
  await page.getByRole('option', { name: 'Hot' }).locator('span').nth(1).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('developer');
  await page.getByRole('textbox', { name: 'Annual Revenue' }).click();
  await page.getByRole('textbox', { name: 'Annual Revenue' }).fill('');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.locator('div').filter({ hasText: 'Success notification.Lead "Mr. Rahul Ghosh" was created.Press Command + F6 to' }).nth(3).click();
  await page.getByRole('button', { name: 'Show more actions' }).click();
  await page.getByRole('menuitem', { name: 'Convert' }).click();
  await page.getByRole('button', { name: 'ck-' }).click();
  await page.getByRole('textbox', { name: 'Opportunity Name *' }).click();
  await page.getByRole('textbox', { name: 'Opportunity Name *' }).fill('ck-dev');
  await page.locator('fieldset:nth-child(3) > div > .entityPanel > .col4').click();
  await page.getByRole('button', { name: 'Convert' }).click();
  await page.getByRole('button', { name: 'Go to Leads' }).click();
  await page.getByRole('link', { name: 'Opportunities' }).click();
  await page.getByText('ck-dev Edit Opportunity Name').click();
});